name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
    # 如果你的主分支叫 master，就把上面的 main 改成 master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: 安装依赖包
        run: npm install
      - name: 开始 Build 打包
        run: npm run build
      - name: 自动发布到 Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
